### ISSUE TITLE
Debugging in VS code shows 'ReferenceError', but the code executes correctly without errors - Unable to see object state

### ISSUE THREAD

**Issue by lukastanisic99** [TypeStrong/ts-node#1818]
It seems there's a visual bug when running the debugger with ts-node. There are no runtime errors and everything executes correctly, but imported variables/objects can't be observed in the VS code debugger. 
Take a look at the picture where it shows the 'ethers' object having an "Uncaught ReferenceError", while you can see the 'Greeter' object that's created through the 'ethers' object. 
![TS-Node](https://user-images.githubusercontent.com/18447664/176892433-c74ea19e-176b-46fb-889f-98381624c351.png)

The exact same object is fully visible when run directly in the node debugger as a javascript file. 

### Search Terms
debug 
Uncaught ReferenceError

### Expected Behavior

To see object/variable state with methods the same way I see the 'Greeter' object in the picture

### Actual Behavior
VS code shows 'Uncaught ReferenceError' when I hover or watch over a variable, but the entire code executes without error. It seems it's just a 'visual' bug.

### Steps to reproduce the problem
Use the debug configuration given here:  https://github.com/TypeStrong/ts-node#visual-studio-code
Try importing a node module and hovering/watching the imported object. 
In my case I used:
import { ethers } from "hardhat";

### Specifications

* ts-node version:v10.8.1
* node version:v14.19.1
* TypeScript version:v4.7.4
* tsconfig.json, if you're using one:
```
{"compilerOptions": {
      "target": "es2018",
      "module": "commonjs",
      "strict": true,
      "esModuleInterop": true,
      "outDir": "dist",
      "declaration": true,
      "sourceMap": true,
      "allowJs": true,
      "resolveJsonModule": true
    },
    "include": ["./src"],}
```
* package.json:
```
{
  "name": "hardhat-project",
  "devDependencies": {
    "@nomiclabs/hardhat-ethers": "^2.0.6",
    "@nomiclabs/hardhat-etherscan": "^3.1.0",
    "@nomiclabs/hardhat-waffle": "^2.0.3",
    "@typechain/ethers-v5": "^7.2.0",
    "@typechain/hardhat": "^2.3.1",
    "@types/chai": "^4.3.1",
    "@types/mocha": "^9.1.1",
    "@types/node": "^12.20.55",
    "@typescript-eslint/eslint-plugin": "^4.33.0",
    "@typescript-eslint/parser": "^4.33.0",
    "chai": "^4.3.6",
    "dotenv": "^16.0.1",
    "eslint": "^7.32.0",
    "eslint-config-prettier": "^8.5.0",
    "eslint-config-standard": "^16.0.3",
    "eslint-plugin-import": "^2.26.0",
    "eslint-plugin-node": "^11.1.0",
    "eslint-plugin-prettier": "^3.4.1",
    "eslint-plugin-promise": "^5.2.0",
    "ethereum-waffle": "^3.4.4",
    "ethers": "^5.6.9",
    "hardhat": "^2.9.9",
    "hardhat-gas-reporter": "^1.0.8",
    "prettier": "^2.7.1",
    "prettier-plugin-solidity": "^1.0.0-beta.19",
    "solhint": "^3.3.7",
    "solidity-coverage": "^0.7.21",
    "ts-node": "^10.8.1",
    "typechain": "^5.2.0",
    "typescript": "^4.7.4"
  }}
```
* Operating system and version: Windows 10 Pro
* If Windows, are you using WSL or WSL2?: WSL2

**Comment by cspotcode** [comment]
My guess is, you're hitting an issue where the compiled output is different than the input.  As far as I know, today's debuggers are not able to map expressions between the source and emitted forms.

A concrete example:
https://www.typescriptlang.org/play?module=1#code/JYWwDg9gTgLgBAbwKYwBZKgZwL5wGZQQhwDkqAhlACYUwkDcAUAMYQB2mEANkgHRcQA5gAoU6LAEp6QA

Source:
```typescript
import {ethers} from 'hardhat';
console.log(ethers);
```

Emit:
```javascript
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const hardhat_1 = require("hardhat");
console.log(hardhat_1.ethers);
```

We can see that the JavaScript being executed is not `console.log(ethers)`; it is `console.log(hardhat_1.ethers)`

So your watch expression will need to be `hardhat_1.ethers`

**Comment by lukastanisic99** [comment]
You're right - watching for hardhat_1 and hardhat_1.ethers works, but in that case I always have to know how it is emitted. The interesting part is when you compile typescript to javascript and map the source, this works even though javascript really does use hardhat_1.ethers underneath. How come it's not mapped in the same way with ts-node? Doesn't it do the exact same thing but JIT?

**Comment by cspotcode** [comment]
Try v10.8.2, we just fixed a sourcemap regression.  Perhaps that is affecting you.

**Comment by lukastanisic99** [comment]
Thanks for the suggestion - I just did that and still the same 😢

**Comment by cspotcode** [comment]
So you are able to use that watch expression when compiling to Commonjs,
and so wanting the same to work with ts-node?  There is some mechanism
within sourcemapping that allows a watch expression of `ethers` to somehow
be translated into `hardhat_1.ethers` within the debugger?

**Comment by lukastanisic99** [comment]
Sorry I thought that worked, but rechecked and it's the same with ts-node. Doesn't matter if it's compiled and mapped or JIT in both cases 'ethers' doesn't work while going through hardhat_1 does. Maybe I had a different config at a time when I thought that worked(was trying a lot of stuff) or I simply imported the full hardhatRuntimeEnvironment and observed that, but can't recreate it now by importing just hardhat ethers😢

**Comment by cspotcode** [comment]
I'm guessing you were using `module: esnext` or something similar, so the imports did not need to be transformed at all.

Either way, I'll go ahead and close this because it seems like everything was working as intended.

**Comment by cspotcode** [comment]
Try v10.8.2, we just fixed a sourcemap regression.  Perhaps that is
affecting you.
