### ISSUE TITLE
Problems with abstract classes.

### ISSUE THREAD

**Issue by DaniGTA** [TypeStrong/ts-node#914]
`error TS2515: Non-abstract class 'TestInfoProvider' does not implement inherited abstract member 'hasUniqueIdForSeasons' from class 'InfoProvider'.`

Code:
```
export default class TestProvider extends ListProvider {
 public hasUniqueIdForSeasons = false;
 constructor() {
        super();
 }
}
```

This shouldnt be a error.

**Comment by blakeembrey** [comment]
Can you create a reproduction? I can’t really help with that code snippet.

**Comment by DaniGTA** [comment]
I can give you access to the repo and maybe you can find what the problem there is. But i cant see any errors there just ts-node seems to see a error.

**Comment by blakeembrey** [comment]
Sure, feel free to add me and any directions I may need to reproduce it. Have you tried it with the typescript compiler directly yet?

**Comment by DaniGTA** [comment]
The typescript compiler works fine. 
The repo: https://github.com/DaniGTA/listManager/invitations
steps to get the error:
`npm i`
`npm test`

if test didnt work you maybe need mocha;
`npm i -g mocha`

**Comment by blakeembrey** [comment]
@DaniGTA I took a look and it appears to be related to registering `ts-node` more than once to compile the same files. I couldn't reproduce the error you reported, but the type errors I did have was fixed once I removed all the `--require ts-node/register` hooks you had added and left only the `tshook.js` in place.

**Comment by DaniGTA** [comment]
k i removed all the  `--require ts-node/register` but the error is still there. I look if it had something todo with my machine and try it on another windows machine but there i have the same problem. 
![image](https://user-images.githubusercontent.com/20490672/69522733-6988b500-0f62-11ea-9cdc-864e2d0caee7.png)

**Comment by blakeembrey** [comment]
@DaniGTA I'm still running into having two too many registrations in `package.json` _and_ `.mocharc.js`. Once I fix those it works. How are you running this without those changes? It's possible to actually replicate this issue I'll need to look on Windows. However, from your stack trace, it looks like you might be compiling a file twice somehow still?

**Comment by blakeembrey** [comment]
The other thing that flags this sort of issue is when your line numbers don't match up in any way. It implies that the code has been compiled twice (e.g. (TS -> JS) -> TS).

**Comment by DaniGTA** [comment]
k i removed the registrations from `package.json` and `.mocharc.js` and it works now. 
I didn't expect mocha to do the same registrations more than once.

Thanks for your help 👍
